### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by amazingtanm** [AI-secure/aug-pe#1]
When I run the command
bash scripts/embeddings.sh --openreview
Report an error
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/sentence-transformers/stsb-roberta-base-v2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3c18433490>: Failed to establish a new connection: [Errno 110] Connection timed out'))"), '(Request ID: c0fb11ea-0999-44d4-a955-5af6026ff738)')
I would like to ask the author how to solve this error

**Comment by amazingtanm** [comment]
Do I need to download stsb-roberta-base-v2 locally?

**Comment by AlphaPav** [comment]
thanks for the question! It seems to be a network connection issue. The code will automatically download stsb-roberta-base-v2 from huggingface: https://huggingface.co/sentence-transformers

**Comment by amazingtanm** [comment]
> thanks for the question! It seems to be a network connection issue. The code will automatically download stsb-roberta-base-v2 from huggingface: https://huggingface.co/sentence-transformers

Thank you so much
I downloaded the stsb-roberta-base-v2 model locally and modified the embedding.sh file
   python pre_comp_emb.py --dataset openreview --model_name_or_path 'DP/aug-pe-main/stsb-roberta-base-v2'
But this time a new error was reported:
  File "/usr/local/miniconda3/envs/augpe/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 77, in __init__
    raise ValueError("Path {} not found".format(model_name_or_path))
ValueError: Path DP/aug-pe-main/stsb-roberta-base-v2 not found
I don't know the reason and would like to ask you to get the answer.

**Comment by AlphaPav** [comment]
Is the relative path "DP/aug-pe-main/stsb-roberta-base-v2" correct for `pre_comp_emb.py`? Alternatively, could you try to specify the model's absolute path?
