### ISSUE TITLE
opensource memory consumption 

### ISSUE THREAD

**Issue by edifice1989** [AI-secure/aug-pe#2]
I oberserve some bizzare memory behavior when using the default model GPT2 to generate synthetic replicas for dataset openreview

The VRAM max out at 24Gb which is the upper limit of my RTX 3090 GPU. I have to kill the process...

Here is the command and log 
bash scripts/hf/openreview/generate.sh

log.log
05/21/2024 00:01:11 AM [MainThread  ] [INFO ]  config: Namespace(api='HFGPT', dataset='openreview', train_data_file='data/openreview/iclr23_reviews_train.csv', train_data_embeddings_file='result/embeddings/stsb-roberta-base-v2/openreview_train_all.embeddings.npz', data_checkpoint_path='', data_checkpoint_step=-1, num_private_samples=-1, result_folder='result/iclr/gpt2_stsb-roberta-base-v2/14000_n0_L7_initL7_var0_openreview_rephrase_tone_rank_len448var0_t1.2', feature_extractor_batch_size=1024, feature_extractor='stsb-roberta-base-v2', noise_multiplier=0.0, lookahead_degree=0, donnot_keep_last_iter=False, combine_divide_L=7, init_combine_divide_L=7, lookahead_self=False, num_nearest_neighbor=1, nn_mode='L2', count_threshold=0.0, compute_fid=True, num_samples_schedule=[14000, 14000, 14000, 14000, 14000, 14000, 14000, 14000, 14000, 14000, 14000], variation_degree_schedule=[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], epochs=10, subsample_one_class=False, select_syn_mode='rank', save_syn_mode='selected', log_online=False, wandb_key='', project='text-API')
05/21/2024 00:01:11 AM [MainThread  ] [INFO ]  API config: Namespace(model_type='gpt2', use_subcategory=True, variation_type='openreview_rephrase_tone', mlm_probability=0.5, output_dir=None, length=448, temperature=1.2, repetition_penalty=1.0, top_k=50, top_p=0.9, num_beams=5, do_sample=True, seed=42, dry_run=False, random_sampling_batch_size=128, variation_batch_size=128, fp16=True, no_cuda=False)
05/21/2024 00:01:12 AM [MainThread  ] [INFO ]  Private_num_classes: 49, Private_num_samples: 8396, Private_num_labels:8396
05/21/2024 00:01:12 AM [MainThread  ] [INFO ]  Extracting features of private data
05/21/2024 00:01:12 AM [MainThread  ] [INFO ]  load features result/embeddings/stsb-roberta-base-v2/openreview_train_all.embeddings.npz
05/21/2024 00:01:12 AM [MainThread  ] [INFO ]  Generating initial samples
05/21/2024 00:01:12 AM [MainThread  ] [INFO ]  should -- simulated generated sequences: 1997

**Comment by AlphaPav** [comment]
Thank you for the question! Could you please try reducing the batch size? For example, you can set:
```
random_sampling_batch_size=8
variation_batch_size=8
```

Please let me know if you encounter any further issues!

**Comment by edifice1989** [comment]
that makes sense!
