### ISSUE TITLE
About computing limitation

### ISSUE THREAD

**Issue by MarkDeng1** [AI-secure/aug-pe#3]
Hi authors,
I would like to reproduce the results. My PC has 96GB RAM with a 24GB GPU. However, when the private data size is 35k, it seems that the memory is exhausted. Does your method have high memory requirements, particularly during the voting stage of calculating embeddings?

Thanks

**Comment by AlphaPav** [comment]
Thank you for the question! Could you please try reducing the batch size? For example, you can set:

```
random_sampling_batch_size=1
variation_batch_size=1
```
Please let me know if you encounter any further issues!

**Comment by MarkDeng1** [comment]
I tried that, but the computer still freezes. Specifically, it freezes at this step:
compute_fid(synthetic_features, all_private_features, args.feature_extractor,
            folder=args.result_folder,  step=start_t-1, log_online=args.log_online)

**Comment by AlphaPav** [comment]
Do you know which steps in the compute_fid function cause it to freeze?

Could you try disabling the `compute_fid` option first? This means removing `--compute_fid` from your command and then attempting to run the program.

Additionally, there is another batch size hyperparameter you can adjust. Try reducing the batch size to 1 by setting:
`feature_extractor_batch_size=1`. 


Let me know if these changes help!
